### ISSUE TITLE
issue on install

### ISSUE THREAD

**Issue by xxx31fr** [QuickBox/QuickBox_Pro#2]
during install, install phpmyadmin and mariadb ok
connect with root to import db : ko (script)
connect with user asked: ko (scipt)
i force install db QB (manual import): ok
reboot and ip/install at the end:

Error connecting to database - check your database connection properties in constants.php file

SQLSTATE[HY000] [1045] Access denied for user 'quickbox'@'localhost' (using password: YES)
PHP Version : 7.0.23-1+ubuntu16.04.1+deb.sury.org+1

Warning: PDO::prepare(): SQLSTATE[00000]: No error: PDO constructor was not called in /srv/rutorrent/home/inc/Configs.php on line 22

Fatal error: Uncaught Error: Call to a member function execute() on null in /srv/rutorrent/home/inc/Configs.php:23 Stack trace: #0 /srv/rutorrent/home/inc/Session.php(515): Configs->getConfig('TRACK_VISITORS') #1 /srv/rutorrent/home/inc/Session.php(78): Session->addActiveGuest('90.3.7.142', 1505746645) #2 /srv/rutorrent/home/inc/Session.php(37): Session->startSession() #3 /srv/rutorrent/home/inc/controller.php(25): Session->__construct(Object(Database)) #4 /srv/rutorrent/home/index.php(6): include('/srv/rutorrent/...') #5 {main} thrown in /srv/rutorrent/home/inc/Configs.php on line 23

hum

**Comment by JMSDOnline** [comment]
There were leftover values from testing. 
This should resolve 

https://github.com/QuickBox/QuickBox_Pro/commit/b826bd611366741cfcd3f3162498505c53224dd4
