### ISSUE TITLE
Installation stuck on "Installing vsftpd ..."

### ISSUE THREAD

**Issue by PastaGringo** [QuickBox/QuickBox_Pro#3]
Ubuntu 16.04

The installation script is waiting confirmation from grub-_something_ autoremove  : 

`apt-get autoremove >>"${OUTTO}" 2>&1` (line 1300)

Added "apt-get autoremove -y" and it works now ;)

**Comment by JMSDOnline** [comment]
Updated. Thank you for the report 👍
